const melody = [
  // START REPEAT
  { duration: 1 / 4, name: "C5" },
  { duration: 1 / 8 + 1 / 16, name: "C5" },
  { duration: 1 / 16, name: "A#5" },
  { duration: 1 / 8, name: "C5" },
  { duration: 1 / 8, name: "A#5" },
  { duration: 1 / 8, name: "G#4" },
  { duration: 1 / 8, name: "G4" },
  { duration: 1 / 16, name: "A#5" },
  { duration: 1 / 16, name: "G#4" },
  { duration: 1 / 16, name: "G4" },
  { duration: 1 / 16, name: "F4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 2, name: "G4" },
  { duration: 1 / 4, name: "A#5" },
  { duration: 1 / 8 + 1 / 16, name: "A#5" },
  { duration: 1 / 16, name: "G#4" },
  { duration: 1 / 8, name: "G4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 16, name: "G4" },
  { duration: 1 / 16, name: "D#4" },
  { duration: 1 / 16, name: "C4" },
  { duration: 1 / 16, name: "D#4" },
  { duration: 1 / 8, name: "G4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 4, name: "D#4" },
  { duration: 1 / 4 + 1 / 8, name: "D4" }, // BLANK
  // END REPEAT

  // ENTER LAST REPEAT

  { duration: 1 / 16, name: "C4" },
  { duration: 1 / 16, name: "D4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "C4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "D4" },
  { duration: 1 / 8, name: "C4" },
  { duration: 1 / 8 + 1 / 16, name: "A#4" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 8, name: "G3" },
  { duration: 1 / 8, name: "G#3" },
  { duration: 1 / 4, name: "A#4" },
  { duration: 1 / 4 + 1 / 8, name: "F3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 8, name: "F3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 8, name: "G3" },
  { duration: 1 / 8, name: "F3" },
  { duration: 1 / 8, name: "D#3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 4, name: "D#3" },
  { duration: 1 / 4, name: "D#3" },
  { duration: 1 / 2 + 1 / 8, name: "D3" },
  { duration: 1 / 16, name: "C4" },
  { duration: 1 / 16, name: "D4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "C4" },
  { duration: 1 / 8, name: "F4" },
  { duration: 1 / 8, name: "D#4" },
  { duration: 1 / 8, name: "D4" },
  { duration: 1 / 8, name: "C4" },
  { duration: 1 / 16, name: "A#4" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 8, name: "A#4" },
  { duration: 1 / 8, name: "G#3" },
  { duration: 1 / 4, name: "G3" },
  { duration: 1 / 4 + 1 / 8, name: "D#3" }, // BLANK
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 8, name: "F3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 8, name: "G3" },
  { duration: 1 / 8, name: "F3" },
  { duration: 1 / 8, name: "D#3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 8, name: "D3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "D3" },
  { duration: 1 / 16, name: "D#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "G#3" },
  { duration: 1 / 16, name: "G3" },
  { duration: 1 / 16, name: "A4" },
  { duration: 1 / 16, name: "B4" },
  { duration: 1 / 16, name: "C4" },
  { duration: 1 / 16, name: "D4" },
  { duration: 1 / 16, name: "D#4" },
  { duration: 1 / 16, name: "F4" },
  { duration: 1 / 16, name: "G4" }, // LOOP NOTE

  // LOOPS OVER
  // { duration: 1 / 4, name: "C5" },
  // { duration: 1 / 8 + 1 / 16, name: "C5" },
  // { duration: 1 / 16, name: "A#5" },
  // { duration: 1 / 8, name: "C5" },
  // { duration: 1 / 8, name: "A#5" },
  // { duration: 1 / 8, name: "G#4" },
  // { duration: 1 / 8, name: "G4" },
  // { duration: 1 / 16, name: "A#5" },
  // { duration: 1 / 16, name: "G#4" },
  // { duration: 1 / 16, name: "G4" },
  // { duration: 1 / 16, name: "F4" },
  // { duration: 1 / 8, name: "D#4" },
  // { duration: 1 / 8, name: "F4" },
  // { duration: 1 / 2, name: "G4" },
];

export default melody;
